AzureWebAppRemoteIpTest/AzureWebAppRemoteIpTest.WebApp/Models/ErrorViewModel.cs
using System;

namespace AzureWebAppRemoteIpTest.WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AzureWebAppRemoteIpTest/AzureWebAppRemoteIpTest.WebApp/Models/RequestPasswordViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AzureWebAppRemoteIpTest.WebApp.Models
{
    public class RequestPasswordViewModel
    {
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Display(Name = "IP Address")]
        public string Ip { get; set; }
    }
}

AzureWebAppRemoteIpTest/AzureWebAppRemoteIpTest.WebApp/Controllers/HomeController.cs
using AzureWebAppRemoteIpTest.WebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AzureWebAppRemoteIpTest.WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AzureWebAppRemoteIpTest/AzureWebAppRemoteIpTest.WebApp/Controllers/RequestPasswordController.cs
using AzureWebAppRemoteIpTest.WebApp.Models;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace AzureWebAppRemoteIpTest.WebApp.Controllers
{
    public class RequestPasswordController : Controller
    {
        public IActionResult Index()
        {
            var connection = HttpContext.Features.Get<IHttpConnectionFeature>();
            IPAddress clientIP = connection.RemoteIpAddress;

            var result = HttpContext.Connection.RemoteIpAddress?.ToString();

            return View(new RequestPasswordViewModel
            {
                Email = "toto@tata.com",
                Ip = result
            });
        }
    }
}

AzureWebAppRemoteIpTest/AzureWebAppRemoteIpTest.WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AzureWebAppRemoteIpTest/AzureWebAppRemoteIpTest.WebApp/Views/RequestPassword/Index.cshtml
@model RequestPasswordViewModel

@{
    ViewData["Title"] = "Request new password Page";
}

<div>
    <h1 class="display-4 text-center">Request Password App</h1>
    <div>
        <ul>
            <li>
                @Model.Email
            </li>
            <li>
                @Model.Ip
            </li>
        </ul>
    </div>
</div>

AzureWebAppRemoteIpTest/AzureWebAppRemoteIpTest.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AzureWebAppRemoteIpTest.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AzureWebAppRemoteIpTest.WebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RequestPassword" asp-action="Index">Password</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AzureWebAppRemoteIpTest.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>